// @vitest-environment node
import { expect, test, vi } from 'vitest';
import type { XaBridge } from '../../app/shared/ipc.ts';
import { channels } from '../../app/shared/ipc.ts';
const mock = vi.hoisted(() => ({ expose: vi.fn(), invoke: vi.fn(async () => {}), on: vi.fn(), remove: vi.fn() }));
vi.mock('electron', () => ({ contextBridge: { exposeInMainWorld: mock.expose }, ipcRenderer: { invoke: mock.invoke, on: mock.on, removeListener: mock.remove } }));
test('桥只开放白名单，不泄露 IPC 事件；取消订阅移除原监听', async () => {
  await import('../../app/preload/index.ts');
  expect(mock.expose.mock.calls[0][0]).toBe('xa');
  const bridge = mock.expose.mock.calls[0][1] as XaBridge;
  expect(Object.isFrozen(bridge)).toBe(true);
  expect(Object.keys(bridge).sort()).toEqual(['appInfo', 'chatCreate', 'chatRename', 'chatSay', 'chatStop', 'cliInstall', 'cliStatus', 'comment', 'connect', 'connectStatus', 'copyIntro', 'decide', 'disconnect', 'getSettings', 'getView', 'modelsKeep', 'modelsRefresh', 'onOpen', 'onUpdate', 'onView', 'redo', 'refreshQuota', 'setAutoUpdateCheck', 'setNetworkAllowed', 'setSettings', 'stop', 'teamSay', 'teamStop', 'updateCheck', 'updateDownload', 'updateRestart']);
  await bridge.decide('x', 'drop'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.decide, 'x', 'drop');
  await bridge.redo('x'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.redo, 'x');
  await bridge.stop('x'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.stop, 'x');
  await bridge.comment('x', '你好'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.comment, 'x', '你好');
  await bridge.teamSay('队', '你好'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.teamSay, '队', '你好');
  await bridge.chatCreate({ project: '项目', members: ['grok:high'] }); expect(mock.invoke).toHaveBeenLastCalledWith(channels.chatCreate, { project: '项目', members: ['grok:high'] });
  await bridge.chatSay('群', '你好'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.chatSay, '群', '你好');
  await bridge.chatStop('群'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.chatStop, '群');
  await bridge.teamStop('队'); expect(mock.invoke).toHaveBeenLastCalledWith(channels.teamStop, '队');
  await bridge.modelsRefresh(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.modelsRefresh);
  await bridge.modelsKeep('codex', ['gpt-6.1-sol']); expect(mock.invoke).toHaveBeenLastCalledWith(channels.modelsKeep, 'codex', ['gpt-6.1-sol']);
  await bridge.refreshQuota(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.quotaRefresh);
  await bridge.setSettings({ notifications: false }); expect(mock.invoke).toHaveBeenLastCalledWith(channels.settingsSet, { notifications: false });
  await bridge.setNetworkAllowed(false); expect(mock.invoke).toHaveBeenLastCalledWith(channels.networkAllowed, false);
  await bridge.cliStatus(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.cliStatus);
  await bridge.cliInstall(true); expect(mock.invoke).toHaveBeenLastCalledWith(channels.cliInstall, true);
  await bridge.appInfo(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.appInfo);
  await bridge.updateCheck(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.updateCheck);
  await bridge.updateDownload(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.updateDownload);
  await bridge.updateRestart(); expect(mock.invoke).toHaveBeenLastCalledWith(channels.updateRestart);
  await bridge.setAutoUpdateCheck(false); expect(mock.invoke).toHaveBeenLastCalledWith(channels.setAutoUpdateCheck, false);
  // 多余参数也要交给后台拒绝，不能在预加载里悄悄吞掉。
  await (bridge.updateCheck as (...args: unknown[]) => Promise<unknown>)(1);
  expect(mock.invoke).toHaveBeenLastCalledWith(channels.updateCheck, 1);
  const update = vi.fn(), unsubscribe = bridge.onUpdate(update), updateListener = mock.on.mock.calls.at(-1)![1] as (event: unknown, value: unknown) => void;
  updateListener({ sender: '不能泄露' }, { phase: 'checking' });
  expect(update).toHaveBeenCalledWith({ phase: 'checking' }); expect(update.mock.calls[0]).toHaveLength(1);
  unsubscribe(); expect(mock.remove).toHaveBeenCalledWith(channels.onUpdate, updateListener);
  const callback = vi.fn(), off = bridge.onOpen(callback), listener = mock.on.mock.calls.at(-1)![1] as (event: unknown, value: unknown) => void;
  listener({ sender: '不得泄露' }, { kind: 'settings' });
  expect(callback).toHaveBeenCalledWith({ kind: 'settings' }); expect(callback.mock.calls[0]).toHaveLength(1);
  off(); expect(mock.remove).toHaveBeenCalledWith(channels.open, listener);
});
